module SecID
  # Unique Product Identifier (UPI, ISO 4914).
  class UPI < Base
    include Checkable
    extend Checkable::ClassMethods

    FULL_NAME: String
    ID_LENGTH: Integer
    EXAMPLE: String
    VALID_CHARS_REGEX: ::Regexp
    ID_REGEX: ::Regexp
    ALPHABET: Array[String]
    ALPHABET_VALUE: Hash[String, Integer]
    GENERATE_CHARSET: Array[String]

    def initialize: (SecID::input upi) -> void
    def calculate_checksum: () -> String
    def self.checksum: (SecID::input id) -> String
    private def self.generate_body: (Random random) -> String

    private

    def components: () -> Hash[Symbol, untyped]
  end
end
