---
sudo: false
cache: bundler
language: ruby

env:
  global:
    - CC_TEST_REPORTER_ID=48c33b2bc3ccdc6dafe9ed76482eca03cde47b922a7859074fc2be791247e5fd

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - truffleruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
  fast_finish: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
