# frozen_string_literal: true

require 'sec_id'

# Generates the RBS signatures for CFI's per-instance dynamic methods
# (Field `<symbol>?` predicates and AttributeSet `<meaning>` readers) from the
# single source of truth, {SecID::CFI::Tables}. RBS has no per-instance typing,
# so the only expressible shape is the union of every name declared on the class.
#
# Shared by the `sig:cfi` rake task (which writes the files) and the drift-guard
# spec (which regenerates in memory and compares). Lives outside `lib/` so it is
# neither shipped in the gem nor part of the typed scope.
module CFISignatureGenerator
  module_function

  GENERATED_HEADER = '# Generated by `rake sig:cfi` from SecID::CFI::Tables. Do not edit by hand.'

  # @return [Array<Symbol>] every symbol a Field may hold, sorted and de-duplicated
  def field_predicate_symbols
    tables = SecID::CFI::Tables
    symbols = tables::CATEGORIES.each_value.map(&:first)
    tables::GROUPS.each_value do |groups|
      groups.each_value { |definition| symbols.concat(group_symbols(definition)) }
    end
    (symbols << :not_applicable).uniq.sort
  end

  # @param definition [Hash] a single group definition
  # @return [Array<Symbol>] the group symbol plus every attribute value symbol
  def group_symbols(definition)
    symbols = [definition[:symbol]]
    definition[:attributes].each do |position|
      next if position.nil?

      position.last.each_value { |value| symbols << value.first }
    end
    symbols
  end

  # @return [Array<Symbol>] every attribute meaning, sorted and de-duplicated
  def attribute_meanings
    meanings = []
    SecID::CFI::Tables::GROUPS.each_value do |groups|
      groups.each_value do |definition|
        definition[:attributes].each { |position| meanings << position.first unless position.nil? }
      end
    end
    meanings.uniq.sort
  end

  # @return [String] full contents of sig/sec_id/cfi/field.rbs
  def field_rbs # rubocop:disable Metrics/MethodLength
    predicates = field_predicate_symbols.map { |symbol| "      def #{symbol}?: () -> bool" }.join("\n")
    <<~RBS
      #{GENERATED_HEADER}
      module SecID
        class CFI < Base
          # A single decoded CFI position (category, group, or one attribute).
          class Field
            attr_reader code: String
            attr_reader name: Symbol
            attr_reader label: String
            attr_reader meaning: Symbol?

            def initialize: (String code, Symbol name, String label, Array[Symbol] domain, ?meaning: Symbol?) -> void
            def to_s: () -> String
            def to_h: () -> Hash[Symbol, untyped]
            def as_json: (*untyped) -> Hash[Symbol, untyped]

            # Per-domain predicates — the union of every symbol a Field may hold. Each
            # instance only answers the symbols in its own domain; an out-of-domain call
            # raises NoMethodError at runtime (RBS can't express per-instance domains).
      #{predicates}
          end
        end
      end
    RBS
  end

  # @return [String] full contents of sig/sec_id/cfi/attribute_set.rbs
  def attribute_set_rbs # rubocop:disable Metrics/MethodLength
    readers = attribute_meanings.map { |meaning| "      def #{meaning}: () -> Field" }.join("\n")
    <<~RBS
      #{GENERATED_HEADER}
      module SecID
        class CFI < Base
          # The ordered collection of decoded attribute Fields.
          class AttributeSet
            include Enumerable[Field]

            # `fields` is typed `untyped` because `#initialize` calls
            # `define_singleton_method(field.meaning)` and `field.meaning` is nilable.
            def initialize: (untyped fields) -> void
            def each: () { (Field) -> void } -> self
                    | () -> Enumerator[Field, self]
            def []: (Symbol meaning) -> Field?
            def empty?: () -> bool
            def to_h: () -> Hash[untyped, untyped]
            def as_json: (*untyped) -> Hash[Symbol, untyped]

            # Per-meaning readers — the union of every attribute meaning. Each instance
            # only answers the meanings actually present; an absent one raises
            # NoMethodError at runtime. Use #[] for the presence-uncertain path.
      #{readers}

            @fields: Array[Field]
          end
        end
      end
    RBS
  end
end
